//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("mailModel", "FK_Attachments_MailInfo", "MailInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebMail2.Model.MailInfo), "Attachments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebMail2.Model.Attachments), true)]

#endregion

namespace WebMail2.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class mailEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“mailEntities”部分中的连接字符串初始化新 mailEntities 对象。
        /// </summary>
        public mailEntities() : base("name=mailEntities", "mailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 mailEntities 对象。
        /// </summary>
        public mailEntities(string connectionString) : base(connectionString, "mailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 mailEntities 对象。
        /// </summary>
        public mailEntities(EntityConnection connection) : base(connection, "mailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Attachments> Attachments
        {
            get
            {
                if ((_Attachments == null))
                {
                    _Attachments = base.CreateObjectSet<Attachments>("Attachments");
                }
                return _Attachments;
            }
        }
        private ObjectSet<Attachments> _Attachments;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MailInfo> MailInfo
        {
            get
            {
                if ((_MailInfo == null))
                {
                    _MailInfo = base.CreateObjectSet<MailInfo>("MailInfo");
                }
                return _MailInfo;
            }
        }
        private ObjectSet<MailInfo> _MailInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MailState> MailState
        {
            get
            {
                if ((_MailState == null))
                {
                    _MailState = base.CreateObjectSet<MailState>("MailState");
                }
                return _MailState;
            }
        }
        private ObjectSet<MailState> _MailState;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<View_AllMail_NoGUID> View_AllMail_NoGUID
        {
            get
            {
                if ((_View_AllMail_NoGUID == null))
                {
                    _View_AllMail_NoGUID = base.CreateObjectSet<View_AllMail_NoGUID>("View_AllMail_NoGUID");
                }
                return _View_AllMail_NoGUID;
            }
        }
        private ObjectSet<View_AllMail_NoGUID> _View_AllMail_NoGUID;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Attachments EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAttachments(Attachments attachments)
        {
            base.AddObject("Attachments", attachments);
        }
    
        /// <summary>
        /// 用于向 MailInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMailInfo(MailInfo mailInfo)
        {
            base.AddObject("MailInfo", mailInfo);
        }
    
        /// <summary>
        /// 用于向 MailState EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMailState(MailState mailState)
        {
            base.AddObject("MailState", mailState);
        }
    
        /// <summary>
        /// 用于向 View_AllMail_NoGUID EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToView_AllMail_NoGUID(View_AllMail_NoGUID view_AllMail_NoGUID)
        {
            base.AddObject("View_AllMail_NoGUID", view_AllMail_NoGUID);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mailModel", Name="Attachments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Attachments : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Attachments 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static Attachments CreateAttachments(global::System.Int32 id)
        {
            Attachments attachments = new Attachments();
            attachments.ID = id;
            return attachments;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MailId
        {
            get
            {
                return _MailId;
            }
            set
            {
                OnMailIdChanging(value);
                ReportPropertyChanging("MailId");
                _MailId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MailId");
                OnMailIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MailId;
        partial void OnMailIdChanging(Nullable<global::System.Int32> value);
        partial void OnMailIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FilePath
        {
            get
            {
                return _FilePath;
            }
            set
            {
                OnFilePathChanging(value);
                ReportPropertyChanging("FilePath");
                _FilePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FilePath");
                OnFilePathChanged();
            }
        }
        private global::System.String _FilePath;
        partial void OnFilePathChanging(global::System.String value);
        partial void OnFilePathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> FileSize
        {
            get
            {
                return _FileSize;
            }
            set
            {
                OnFileSizeChanging(value);
                ReportPropertyChanging("FileSize");
                _FileSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FileSize");
                OnFileSizeChanged();
            }
        }
        private Nullable<global::System.Double> _FileSize;
        partial void OnFileSizeChanging(Nullable<global::System.Double> value);
        partial void OnFileSizeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileId
        {
            get
            {
                return _FileId;
            }
            set
            {
                OnFileIdChanging(value);
                ReportPropertyChanging("FileId");
                _FileId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileId");
                OnFileIdChanged();
            }
        }
        private global::System.String _FileId;
        partial void OnFileIdChanging(global::System.String value);
        partial void OnFileIdChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mailModel", "FK_Attachments_MailInfo", "MailInfo")]
        public MailInfo MailInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailInfo>("mailModel.FK_Attachments_MailInfo", "MailInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailInfo>("mailModel.FK_Attachments_MailInfo", "MailInfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MailInfo> MailInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailInfo>("mailModel.FK_Attachments_MailInfo", "MailInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MailInfo>("mailModel.FK_Attachments_MailInfo", "MailInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mailModel", Name="MailInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MailInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MailInfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static MailInfo CreateMailInfo(global::System.Int32 id)
        {
            MailInfo mailInfo = new MailInfo();
            mailInfo.ID = id;
            return mailInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _Level;
        partial void OnLevelChanging(Nullable<global::System.Int32> value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SendFromName
        {
            get
            {
                return _SendFromName;
            }
            set
            {
                OnSendFromNameChanging(value);
                ReportPropertyChanging("SendFromName");
                _SendFromName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SendFromName");
                OnSendFromNameChanged();
            }
        }
        private global::System.String _SendFromName;
        partial void OnSendFromNameChanging(global::System.String value);
        partial void OnSendFromNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SendFromId
        {
            get
            {
                return _SendFromId;
            }
            set
            {
                OnSendFromIdChanging(value);
                ReportPropertyChanging("SendFromId");
                _SendFromId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SendFromId");
                OnSendFromIdChanged();
            }
        }
        private global::System.String _SendFromId;
        partial void OnSendFromIdChanging(global::System.String value);
        partial void OnSendFromIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddresseeIds
        {
            get
            {
                return _AddresseeIds;
            }
            set
            {
                OnAddresseeIdsChanging(value);
                ReportPropertyChanging("AddresseeIds");
                _AddresseeIds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddresseeIds");
                OnAddresseeIdsChanged();
            }
        }
        private global::System.String _AddresseeIds;
        partial void OnAddresseeIdsChanging(global::System.String value);
        partial void OnAddresseeIdsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SendTime
        {
            get
            {
                return _SendTime;
            }
            set
            {
                OnSendTimeChanging(value);
                ReportPropertyChanging("SendTime");
                _SendTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendTime");
                OnSendTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _SendTime;
        partial void OnSendTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnSendTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDraft
        {
            get
            {
                return _IsDraft;
            }
            set
            {
                OnIsDraftChanging(value);
                ReportPropertyChanging("IsDraft");
                _IsDraft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDraft");
                OnIsDraftChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDraft;
        partial void OnIsDraftChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDraftChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddresseeNames
        {
            get
            {
                return _AddresseeNames;
            }
            set
            {
                OnAddresseeNamesChanging(value);
                ReportPropertyChanging("AddresseeNames");
                _AddresseeNames = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddresseeNames");
                OnAddresseeNamesChanged();
            }
        }
        private global::System.String _AddresseeNames;
        partial void OnAddresseeNamesChanging(global::System.String value);
        partial void OnAddresseeNamesChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mailModel", "FK_Attachments_MailInfo", "Attachments")]
        public EntityCollection<Attachments> Attachments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Attachments>("mailModel.FK_Attachments_MailInfo", "Attachments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Attachments>("mailModel.FK_Attachments_MailInfo", "Attachments", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mailModel", Name="MailState")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MailState : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MailState 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static MailState CreateMailState(global::System.Decimal id)
        {
            MailState mailState = new MailState();
            mailState.ID = id;
            return mailState;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MailId
        {
            get
            {
                return _MailId;
            }
            set
            {
                OnMailIdChanging(value);
                ReportPropertyChanging("MailId");
                _MailId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MailId");
                OnMailIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MailId;
        partial void OnMailIdChanging(Nullable<global::System.Int32> value);
        partial void OnMailIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UName
        {
            get
            {
                return _UName;
            }
            set
            {
                OnUNameChanging(value);
                ReportPropertyChanging("UName");
                _UName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UName");
                OnUNameChanged();
            }
        }
        private global::System.String _UName;
        partial void OnUNameChanging(global::System.String value);
        partial void OnUNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Uid
        {
            get
            {
                return _Uid;
            }
            set
            {
                OnUidChanging(value);
                ReportPropertyChanging("Uid");
                _Uid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Uid");
                OnUidChanged();
            }
        }
        private global::System.String _Uid;
        partial void OnUidChanging(global::System.String value);
        partial void OnUidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRead
        {
            get
            {
                return _IsRead;
            }
            set
            {
                OnIsReadChanging(value);
                ReportPropertyChanging("IsRead");
                _IsRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRead");
                OnIsReadChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRead;
        partial void OnIsReadChanging(Nullable<global::System.Boolean> value);
        partial void OnIsReadChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReadTime
        {
            get
            {
                return _ReadTime;
            }
            set
            {
                OnReadTimeChanging(value);
                ReportPropertyChanging("ReadTime");
                _ReadTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadTime");
                OnReadTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReadTime;
        partial void OnReadTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnReadTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDel
        {
            get
            {
                return _IsDel;
            }
            set
            {
                OnIsDelChanging(value);
                ReportPropertyChanging("IsDel");
                _IsDel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDel");
                OnIsDelChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDel;
        partial void OnIsDelChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DelTime
        {
            get
            {
                return _DelTime;
            }
            set
            {
                OnDelTimeChanging(value);
                ReportPropertyChanging("DelTime");
                _DelTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DelTime");
                OnDelTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DelTime;
        partial void OnDelTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDelTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDustbinInbox
        {
            get
            {
                return _IsDustbinInbox;
            }
            set
            {
                OnIsDustbinInboxChanging(value);
                ReportPropertyChanging("IsDustbinInbox");
                _IsDustbinInbox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDustbinInbox");
                OnIsDustbinInboxChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDustbinInbox;
        partial void OnIsDustbinInboxChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDustbinInboxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DustbinTimeInbox
        {
            get
            {
                return _DustbinTimeInbox;
            }
            set
            {
                OnDustbinTimeInboxChanging(value);
                ReportPropertyChanging("DustbinTimeInbox");
                _DustbinTimeInbox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DustbinTimeInbox");
                OnDustbinTimeInboxChanged();
            }
        }
        private Nullable<global::System.DateTime> _DustbinTimeInbox;
        partial void OnDustbinTimeInboxChanging(Nullable<global::System.DateTime> value);
        partial void OnDustbinTimeInboxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDustbinOutbox
        {
            get
            {
                return _IsDustbinOutbox;
            }
            set
            {
                OnIsDustbinOutboxChanging(value);
                ReportPropertyChanging("IsDustbinOutbox");
                _IsDustbinOutbox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDustbinOutbox");
                OnIsDustbinOutboxChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDustbinOutbox;
        partial void OnIsDustbinOutboxChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDustbinOutboxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DustbinTimeOutbox
        {
            get
            {
                return _DustbinTimeOutbox;
            }
            set
            {
                OnDustbinTimeOutboxChanging(value);
                ReportPropertyChanging("DustbinTimeOutbox");
                _DustbinTimeOutbox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DustbinTimeOutbox");
                OnDustbinTimeOutboxChanged();
            }
        }
        private Nullable<global::System.DateTime> _DustbinTimeOutbox;
        partial void OnDustbinTimeOutboxChanging(Nullable<global::System.DateTime> value);
        partial void OnDustbinTimeOutboxChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mailModel", Name="View_AllMail_NoGUID")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class View_AllMail_NoGUID : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 View_AllMail_NoGUID 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static View_AllMail_NoGUID CreateView_AllMail_NoGUID(global::System.Int32 id)
        {
            View_AllMail_NoGUID view_AllMail_NoGUID = new View_AllMail_NoGUID();
            view_AllMail_NoGUID.ID = id;
            return view_AllMail_NoGUID;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> mid
        {
            get
            {
                return _mid;
            }
            set
            {
                OnmidChanging(value);
                ReportPropertyChanging("mid");
                _mid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mid");
                OnmidChanged();
            }
        }
        private Nullable<global::System.Decimal> _mid;
        partial void OnmidChanging(Nullable<global::System.Decimal> value);
        partial void OnmidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MailId
        {
            get
            {
                return _MailId;
            }
            set
            {
                OnMailIdChanging(value);
                ReportPropertyChanging("MailId");
                _MailId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MailId");
                OnMailIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MailId;
        partial void OnMailIdChanging(Nullable<global::System.Int32> value);
        partial void OnMailIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _Level;
        partial void OnLevelChanging(Nullable<global::System.Int32> value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SendFromName
        {
            get
            {
                return _SendFromName;
            }
            set
            {
                OnSendFromNameChanging(value);
                ReportPropertyChanging("SendFromName");
                _SendFromName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SendFromName");
                OnSendFromNameChanged();
            }
        }
        private global::System.String _SendFromName;
        partial void OnSendFromNameChanging(global::System.String value);
        partial void OnSendFromNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SendFromId
        {
            get
            {
                return _SendFromId;
            }
            set
            {
                OnSendFromIdChanging(value);
                ReportPropertyChanging("SendFromId");
                _SendFromId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SendFromId");
                OnSendFromIdChanged();
            }
        }
        private global::System.String _SendFromId;
        partial void OnSendFromIdChanging(global::System.String value);
        partial void OnSendFromIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddresseeIds
        {
            get
            {
                return _AddresseeIds;
            }
            set
            {
                OnAddresseeIdsChanging(value);
                ReportPropertyChanging("AddresseeIds");
                _AddresseeIds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddresseeIds");
                OnAddresseeIdsChanged();
            }
        }
        private global::System.String _AddresseeIds;
        partial void OnAddresseeIdsChanging(global::System.String value);
        partial void OnAddresseeIdsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SendTime
        {
            get
            {
                return _SendTime;
            }
            set
            {
                OnSendTimeChanging(value);
                ReportPropertyChanging("SendTime");
                _SendTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendTime");
                OnSendTimeChanged();

            }
        }
        private Nullable<global::System.DateTime> _SendTime;
        partial void OnSendTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnSendTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDraft
        {
            get
            {
                return _IsDraft;
            }
            set
            {
                OnIsDraftChanging(value);
                ReportPropertyChanging("IsDraft");
                _IsDraft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDraft");
                OnIsDraftChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDraft;
        partial void OnIsDraftChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDraftChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddresseeNames
        {
            get
            {
                return _AddresseeNames;
            }
            set
            {
                OnAddresseeNamesChanging(value);
                ReportPropertyChanging("AddresseeNames");
                _AddresseeNames = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddresseeNames");
                OnAddresseeNamesChanged();
            }
        }
        private global::System.String _AddresseeNames;
        partial void OnAddresseeNamesChanging(global::System.String value);
        partial void OnAddresseeNamesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UName
        {
            get
            {
                return _UName;
            }
            set
            {
                OnUNameChanging(value);
                ReportPropertyChanging("UName");
                _UName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UName");
                OnUNameChanged();
            }
        }
        private global::System.String _UName;
        partial void OnUNameChanging(global::System.String value);
        partial void OnUNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Uid
        {
            get
            {
                return _Uid;
            }
            set
            {
                OnUidChanging(value);
                ReportPropertyChanging("Uid");
                _Uid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Uid");
                OnUidChanged();
            }
        }
        private global::System.String _Uid;
        partial void OnUidChanging(global::System.String value);
        partial void OnUidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRead
        {
            get
            {
                return _IsRead;
            }
            set
            {
                OnIsReadChanging(value);
                ReportPropertyChanging("IsRead");
                _IsRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRead");
                OnIsReadChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRead;
        partial void OnIsReadChanging(Nullable<global::System.Boolean> value);
        partial void OnIsReadChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReadTime
        {
            get
            {
                return _ReadTime;
            }
            set
            {
                OnReadTimeChanging(value);
                ReportPropertyChanging("ReadTime");
                _ReadTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadTime");
                OnReadTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReadTime;
        partial void OnReadTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnReadTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDel
        {
            get
            {
                return _IsDel;
            }
            set
            {
                OnIsDelChanging(value);
                ReportPropertyChanging("IsDel");
                _IsDel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDel");
                OnIsDelChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDel;
        partial void OnIsDelChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StateID
        {
            get
            {
                return _StateID;
            }
            set
            {
                OnStateIDChanging(value);
                ReportPropertyChanging("StateID");
                _StateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StateID");
                OnStateIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _StateID;
        partial void OnStateIDChanging(Nullable<global::System.Decimal> value);
        partial void OnStateIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DelTime
        {
            get
            {
                return _DelTime;
            }
            set
            {
                OnDelTimeChanging(value);
                ReportPropertyChanging("DelTime");
                _DelTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DelTime");
                OnDelTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DelTime;
        partial void OnDelTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDelTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDustbinInbox
        {
            get
            {
                return _IsDustbinInbox;
            }
            set
            {
                OnIsDustbinInboxChanging(value);
                ReportPropertyChanging("IsDustbinInbox");
                _IsDustbinInbox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDustbinInbox");
                OnIsDustbinInboxChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDustbinInbox;
        partial void OnIsDustbinInboxChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDustbinInboxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DustbinTimeInbox
        {
            get
            {
                return _DustbinTimeInbox;
            }
            set
            {
                OnDustbinTimeInboxChanging(value);
                ReportPropertyChanging("DustbinTimeInbox");
                _DustbinTimeInbox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DustbinTimeInbox");
                OnDustbinTimeInboxChanged();
            }
        }
        private Nullable<global::System.DateTime> _DustbinTimeInbox;
        partial void OnDustbinTimeInboxChanging(Nullable<global::System.DateTime> value);
        partial void OnDustbinTimeInboxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDustbinOutbox
        {
            get
            {
                return _IsDustbinOutbox;
            }
            set
            {
                OnIsDustbinOutboxChanging(value);
                ReportPropertyChanging("IsDustbinOutbox");
                _IsDustbinOutbox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDustbinOutbox");
                OnIsDustbinOutboxChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDustbinOutbox;
        partial void OnIsDustbinOutboxChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDustbinOutboxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DustbinTimeOutbox
        {
            get
            {
                return _DustbinTimeOutbox;
            }
            set
            {
                OnDustbinTimeOutboxChanging(value);
                ReportPropertyChanging("DustbinTimeOutbox");
                _DustbinTimeOutbox = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DustbinTimeOutbox");
                OnDustbinTimeOutboxChanged();
            }
        }
        private Nullable<global::System.DateTime> _DustbinTimeOutbox;
        partial void OnDustbinTimeOutboxChanging(Nullable<global::System.DateTime> value);
        partial void OnDustbinTimeOutboxChanged();

        #endregion

    
    }

    #endregion

    
}
